MeuAppCore/Models/ErrorViewModel.cs
using System;

namespace MeuAppCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MeuAppCore/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MeuAppCore.Controllers
{
    public class HelloWorldController : Controller
    {
        // 
        // GET: /HelloWorld/

        public IActionResult Index()
        {
            return View();
        }

        string[] movies = new string[] {
            "A rede social",
            "Harry Potter",
            "Avatar",
            "Ladrão de raios"
        };

        string[] fotos = new string[]
        {
            "https://upload.wikimedia.org/wikipedia/pt/b/b2/A_Rede_Social.png",
            "https://static1.purebreak.com.br/articles/6/91/90/6/@/353206-de-harry-potter-a-descendentes-faca-diapo-1.jpg",
            "https://i.correiobraziliense.com.br/D7nA7yEBHX5e3Qgc7iQ7nMJYM5I=/675x/smart/imgsapp2.correiobraziliense.com.br/app/noticia_127983242361/2019/10/04/794834/20191004154953157610i.jpg",
            "https://http2.mlstatic.com/percy-jackson-e-os-olimpianos-o-ladro-de-raios-D_NQ_NP_656736-MLB28873887615_122018-F.jpg"
        };

        string[] autor = new string[]
        {
            "Ben Mezrich",
            "J. K. Rowling",
            "James Cameron",
            "Rick Riordan"
        };

        public IActionResult Welcome()
        {
            ViewData["filme"] = movies;
            ViewData["autor"] = autor;
            ViewData["fotos"] = fotos;
            ViewData["NumTimes"] = movies.Length;

            return View();
        }
    }
}

MeuAppCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MeuAppCore.Models;

namespace MeuAppCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MeuAppCore/Controllers/NovoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MeuAppCore.Controllers
{
    public class NovoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MinhaAcao()
        {
            return View();
        }
    }
}

MeuAppCore/Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Movie List";
}
<title>@ViewData["Title"] - Movie App</title>
<h2>My Movie List</h2>

<p>Hello from our View Template!</p>

MeuAppCore/Views/HelloWorld/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
    string[] filmes = (string[])ViewData["filme"];
    string[] fotos = (string[])ViewData["fotos"];
    string[] autor = (string[])ViewData["autor"];
}


<script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>

<h2>Filmes</h2>

<ul class="movies">
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li data-img="@fotos[i]" data-name="@filmes[i]"><img src="@fotos[i]"/> <span>@filmes[i]</span><br /><span class="autor">@autor[i]</span>
    </li>
    }
</ul>


<style>
    .movies li {
        list-style: none;
        margin: 20px;
        transition: 0.4s;
        display: inline-table;
        padding: 5px;
        width: 200px;
        max-width: 900px;
        transform: scale(1.15);
        cursor: pointer;
        border-radius: 2px;
        background: #eee;
        box-shadow: -2px 1px 2px rgba(0,0,0,.30);
    }


    .movies li span{
        margin-left: 5px;
        position: relative;
        position: absolute;
        top: 20px;
        left: 72px;
    }

    .autor{
        top: 50px !important;
    }

    .movies li:hover{
        background: #ccc;
        transform: scale(1.2);
    }

    img{
        width: 60px;
        transform: scale(1.1);
        height: 100px;
        object-fit: cover;
        border-solid: 1px solid #ccc;
        position: relative;
        left: -2px;
    }

    .aberto{
        position: fixed;
        width: 100%;
        height: 100%;
        opacity: 1;
        z-index: -10;
        background: rgba(0,0,0,.60);
        top: 0px;
        left: 0px;
        display: none;
    }

        .aberto img {
            position: relative;
            width: 400px;
            max-width: 250px;
            height: 400px;
            z-index: 99999999;
            box-shadow: -2px 1px 2px rgba(0,0,0,.50);
            left: 4px;
            transform: scale(1.2);
            top: -25px;
        }

    @@-webkit-keyframes zoom {
        0% {
            transform: scale(0.5) translate(-50%, -50%);
        }
        50% {
            transform: scale(1.2,1.2) translate(-50%, -50%);
        }
        100% {
            transform: scale(1) translate(-50%, -50%);
        }
    }

    .sair {
        position: fixed;
        width: 100%;
        height: 100%;
        opacity: 1;
        z-index: 40000;
        background: transparent;
        top: 0px;
        left: 0px;
        display: block;
        cursor: pointer;
    }

    .info {
        position: fixed;
        transform: translate(-50%, -50%);
        top: 50%;
        left: 50%;
        background: #ddd;
        padding: 6px;
        animation: zoom 0.4s;
        box-shadow: -2px 1px 2px rgba(0,0,0,.30);
        overflow: hidden;
        z-index: 999999999;
    }

    .info h1{
        padding: 4px;
    }
</style>

<div class="aberto">
    <div class="before">

    </div>
</div>

<script>
    
    function zoom() {
        $(".movies li").click(function () {
            const image = $(this).data("img");
            const name = $(this).data("name");
            $(".aberto").css({
                "z-index": 8000,
                "display": "block"
            });
            $(".aberto .before").before(`<div class="info"> <img src="${image}"/> <h1>${name}</h1> </div>`);
            $(".aberto .before").before(`<div class="sair"></div>`);
            sair();
        });
    }
    

    function sair() {
        $(".aberto .sair").click(function () {
            $(".aberto").html("<div class='before'></div>");
            $(".aberto").css({
                "z-index": 1000,
                "display": "none"
            });
        });
    }

    zoom();
</script>

MeuAppCore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MeuAppCore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MeuAppCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MeuAppCore/Views/Novo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

MeuAppCore/Views/Novo/MinhaAcao.cshtml
@{
    ViewData["Title"] = "MinhaAcao";
}

<h2>MinhaAcao</h2>

MeuAppCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeuAppCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MeuAppCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="HelloWorld" asp-action="Index">Hello World</a></li>
                    <li><a asp-area="" asp-controller="HelloWorld" asp-action="Welcome">Welcome</a></li>
                    <li><a asp-area="" asp-controller="Novo" asp-action="Index">Novo que fiz</a></li>
                    <li><a asp-area="" asp-controller="Novo" asp-action="MinhaAcao">Minha</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - MeuAppCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>